### ISSUE TITLE
.data.data in PUT request body

### ISSUE THREAD

**Issue by theavicaster** [Me-and-the-bois/FlexMart#7]
```
warehouse.js

router.put('/productList/update', (req,res,next) => {
    console.log('Product Id to be updated:', req.body.data.data.pid);
    ProductList.updateOne({'pid': req.body.data.data.pid}, {pimg: req.body.data.data.pimg,ptype: req.body.data.data.ptype,pid: req.body.data.data.pid,pname: req.body.data.data.pname,pno: req.body.data.data.pno,pprice: req.body.data.data.pprice}).then(result => {
        console.log(result._id);
        res.status(201).json({message: "Product updated successfully!!"});
      });
})
```

The .data.data part is redundant.

**Comment by Noob0799** [comment]
axios.put("http://localhost:5000/warehouse/productList/update", {data: {data: productData}})
                        .then(res => {
                            console.log(res.data.message);
                            this.props.get();
                            document.getElementById('close').click();
                        });

actually its because of the way i have sent the data from the frontend. so the .data.data part. wont work otherwise.

**Comment by theavicaster** [comment]
Alright. Please modify the update endpoints in admin.js
